version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: junior
      POSTGRES_PASSWORD: nestapi1234
      POSTGRES_DB: mydatabase
    networks:
      - junior-network
networks:
  junior-network:
  
